/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.CardLayout;

/**
 *
 * @author Suazo
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_main = new javax.swing.JPanel();
        jp_laberinto = new javax.swing.JPanel();
        jp_LabGraphics = jp_LabGraphics = new Laberinto(500, 400);
        jp_cargarLab = new javax.swing.JButton();
        jp_desempeno = new javax.swing.JPanel();
        jp_matematicas = new javax.swing.JPanel();
        jp_compresion = new javax.swing.JPanel();
        jp_menor = new javax.swing.JPanel();
        jp_arbol = new javax.swing.JPanel();
        jp_header = new javax.swing.JPanel();
        jb_laberinto = new javax.swing.JButton();
        jb_desempeno = new javax.swing.JButton();
        jb_matematicas = new javax.swing.JButton();
        jb_compresion = new javax.swing.JButton();
        jb_MenorCosto = new javax.swing.JButton();
        jb_arbol = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_main.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jp_main.setName("Main"); // NOI18N
        jp_main.setLayout(new java.awt.CardLayout());

        jp_LabGraphics.setBackground(new java.awt.Color(255, 255, 255));
        jp_LabGraphics.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jp_LabGraphics.setPreferredSize(new java.awt.Dimension(500, 400));

        javax.swing.GroupLayout jp_LabGraphicsLayout = new javax.swing.GroupLayout(jp_LabGraphics);
        jp_LabGraphics.setLayout(jp_LabGraphicsLayout);
        jp_LabGraphicsLayout.setHorizontalGroup(
            jp_LabGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        jp_LabGraphicsLayout.setVerticalGroup(
            jp_LabGraphicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jp_cargarLab.setText("Cargar Laberinto");
        jp_cargarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_cargarLabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_laberintoLayout = new javax.swing.GroupLayout(jp_laberinto);
        jp_laberinto.setLayout(jp_laberintoLayout);
        jp_laberintoLayout.setHorizontalGroup(
            jp_laberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_laberintoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_cargarLab)
                .addGap(286, 286, 286))
            .addGroup(jp_laberintoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jp_LabGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jp_laberintoLayout.setVerticalGroup(
            jp_laberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_laberintoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jp_LabGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_cargarLab)
                .addContainerGap())
        );

        jp_main.add(jp_laberinto, "laberinto");

        javax.swing.GroupLayout jp_desempenoLayout = new javax.swing.GroupLayout(jp_desempeno);
        jp_desempeno.setLayout(jp_desempenoLayout);
        jp_desempenoLayout.setHorizontalGroup(
            jp_desempenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jp_desempenoLayout.setVerticalGroup(
            jp_desempenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jp_main.add(jp_desempeno, "desempeno");

        javax.swing.GroupLayout jp_matematicasLayout = new javax.swing.GroupLayout(jp_matematicas);
        jp_matematicas.setLayout(jp_matematicasLayout);
        jp_matematicasLayout.setHorizontalGroup(
            jp_matematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jp_matematicasLayout.setVerticalGroup(
            jp_matematicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jp_main.add(jp_matematicas, "matematicas");

        javax.swing.GroupLayout jp_compresionLayout = new javax.swing.GroupLayout(jp_compresion);
        jp_compresion.setLayout(jp_compresionLayout);
        jp_compresionLayout.setHorizontalGroup(
            jp_compresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jp_compresionLayout.setVerticalGroup(
            jp_compresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jp_main.add(jp_compresion, "compresion");

        javax.swing.GroupLayout jp_menorLayout = new javax.swing.GroupLayout(jp_menor);
        jp_menor.setLayout(jp_menorLayout);
        jp_menorLayout.setHorizontalGroup(
            jp_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jp_menorLayout.setVerticalGroup(
            jp_menorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jp_main.add(jp_menor, "menor");

        javax.swing.GroupLayout jp_arbolLayout = new javax.swing.GroupLayout(jp_arbol);
        jp_arbol.setLayout(jp_arbolLayout);
        jp_arbolLayout.setHorizontalGroup(
            jp_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jp_arbolLayout.setVerticalGroup(
            jp_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jp_main.add(jp_arbol, "arbol");

        jp_header.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jp_header.setName("Header"); // NOI18N

        jb_laberinto.setText("Laberinto");
        jb_laberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_laberintoActionPerformed(evt);
            }
        });

        jb_desempeno.setText("Evaluación de Desempeño");
        jb_desempeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_desempenoActionPerformed(evt);
            }
        });

        jb_matematicas.setText("Expresiones Matemáticas");
        jb_matematicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_matematicasActionPerformed(evt);
            }
        });

        jb_compresion.setText("Compresión de Archivos de Texto");
        jb_compresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_compresionActionPerformed(evt);
            }
        });

        jb_MenorCosto.setText("Menor Costo");
        jb_MenorCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_MenorCostoActionPerformed(evt);
            }
        });

        jb_arbol.setText("Árbol de Expansión");
        jb_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_arbolActionPerformed(evt);
            }
        });

        jb_salir.setText("Salir");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jp_headerLayout = new javax.swing.GroupLayout(jp_header);
        jp_header.setLayout(jp_headerLayout);
        jp_headerLayout.setHorizontalGroup(
            jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_laberinto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_desempeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_matematicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_compresion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_MenorCosto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_arbol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_salir)
                .addContainerGap())
        );
        jp_headerLayout.setVerticalGroup(
            jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_headerLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jb_matematicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addComponent(jb_laberinto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_desempeno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jb_compresion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_MenorCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jb_arbol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jb_salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jp_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jp_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_laberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_laberintoActionPerformed
        CardLayout card = (CardLayout) jp_main.getLayout();
        card.show(jp_main, "laberinto");
    }//GEN-LAST:event_jb_laberintoActionPerformed

    private void jb_desempenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_desempenoActionPerformed
        CardLayout card = (CardLayout) jp_main.getLayout();
        card.show(jp_main, "desempeno");
    }//GEN-LAST:event_jb_desempenoActionPerformed

    private void jb_matematicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_matematicasActionPerformed
        CardLayout card = (CardLayout) jp_main.getLayout();
        card.show(jp_main, "matematicas");
    }//GEN-LAST:event_jb_matematicasActionPerformed

    private void jb_compresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_compresionActionPerformed
        CardLayout card = (CardLayout) jp_main.getLayout();
        card.show(jp_main, "compresion");
    }//GEN-LAST:event_jb_compresionActionPerformed

    private void jb_MenorCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_MenorCostoActionPerformed
        CardLayout card = (CardLayout) jp_main.getLayout();
        card.show(jp_main, "menor");
    }//GEN-LAST:event_jb_MenorCostoActionPerformed

    private void jb_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_arbolActionPerformed
        CardLayout card = (CardLayout) jp_main.getLayout();
        card.show(jp_main, "arbol");
    }//GEN-LAST:event_jb_arbolActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jp_cargarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_cargarLabActionPerformed
        jp_LabGraphics = new Laberinto(jp_LabGraphics.getWidth(), jp_LabGraphics.getHeight());
    }//GEN-LAST:event_jp_cargarLabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jb_MenorCosto;
    private javax.swing.JButton jb_arbol;
    private javax.swing.JButton jb_compresion;
    private javax.swing.JButton jb_desempeno;
    private javax.swing.JButton jb_laberinto;
    private javax.swing.JButton jb_matematicas;
    private javax.swing.JButton jb_salir;
    private javax.swing.JPanel jp_LabGraphics;
    private javax.swing.JPanel jp_arbol;
    private javax.swing.JButton jp_cargarLab;
    private javax.swing.JPanel jp_compresion;
    private javax.swing.JPanel jp_desempeno;
    private javax.swing.JPanel jp_header;
    private javax.swing.JPanel jp_laberinto;
    private javax.swing.JPanel jp_main;
    private javax.swing.JPanel jp_matematicas;
    private javax.swing.JPanel jp_menor;
    // End of variables declaration//GEN-END:variables
}
